# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b225d59920eb2b06086b6199aff489a29502a13b315268bb01c4d23df5d021cd97a110b6ccd301d107e5b2fd4d51da2bffbd5046abe66d7b051eb0bd77139af9

test:
  secret_key_base: 881aa595e03196a50d0a8d38dee95584d3690d62e20b15d1adb74044398cd4c6c6c18d90e9bcb99eb853320d05d36f58a1da54e428dc07c4c8ce6b1cde4debb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
